package com.agropharm.Entities.enums;

public enum OrderStatus {
    CREATED,
    CANCELLED,
    APPROVED,
    COLLECTED_FOR_DELIVERY,
    DELIVERY_COMPLETED_SUCCESSFULLY,
    DELIVERY_COMPLETED_UNSUCCESSFULLY,
    REJECTED
}
